version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: flylight
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: -p 5432
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
